USE [master]
GO

/****** Object:  Database [Tekus]    Script Date: 31/08/2024 10:40:09 p. m. ******/
CREATE DATABASE [Tekus]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Tekus', FILENAME = N'C:\Program Files\Microsoft SQL Server\Tekus\Data\Tekus.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Tekus_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\Tekus\Data\Tekus_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Tekus].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Tekus] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Tekus] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Tekus] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Tekus] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Tekus] SET ARITHABORT OFF 
GO

ALTER DATABASE [Tekus] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Tekus] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Tekus] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Tekus] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Tekus] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Tekus] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Tekus] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Tekus] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Tekus] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Tekus] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Tekus] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Tekus] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Tekus] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Tekus] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Tekus] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Tekus] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Tekus] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Tekus] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Tekus] SET  MULTI_USER 
GO

ALTER DATABASE [Tekus] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Tekus] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Tekus] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Tekus] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Tekus] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Tekus] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Tekus] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Tekus] SET  READ_WRITE 
GO


